package io.tapstate.core.catalog;

import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

import static java.util.Map.entry;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * The two populations in the shipped catalog that carry no trustworthy mode signal, each pinned as a
 * checked-in baseline. Reads only this module's own resources, so it runs in every build - no
 * connectors checkout, no PDK.
 *
 * <p><strong>Two buckets, not one, and they are disjoint.</strong> A row can fail to have a
 * trustworthy mode in two different ways: nothing resolved at all (no modes), or something resolved
 * that nobody checked (modes, all derived, on a connector derivation cannot answer for). They need
 * separate baselines because they are separate gaps with separate fixes, and because folding them
 * together hides the move between them: a connector whose jar starts building goes from the first
 * bucket to the second - shipping a wrong claim where it previously shipped none - while a single
 * total stays exactly where it was.
 *
 * <p><strong>Growth is what this fails on; shrinking is not.</strong> An entry leaves a bucket by
 * getting a declaration, which is the whole point of the overlay, so a smaller bucket is the intended
 * direction and must never be a red build. An entry joining one is the direction nothing else
 * reports: the catalog is regenerated wholesale, so a connector that quietly stopped resolving its
 * modes, or started resolving the wrong ones, reads in the diff exactly like any other regeneration.
 * Updating a baseline is therefore an explicit commit by a person who looked, never a rebase.
 *
 * <p><strong>Why an id cannot simply be moved out today.</strong> The exit is a declaration in the
 * overlay, and an overlay entry and the snapshot entry it governs have to land together - the
 * reconciliation gate compares them and reddens if they disagree. The snapshot is only regenerated by
 * a rebuild with the connectors present, so until such a rebuild runs, every id below stays here.
 */
class ModeSignalBaselineTest {

    private final TapstateCatalog catalog = TapstateCatalog.load();

    /**
     * Why a connector resolved no mode at all. Stated per id rather than counted, because the two
     * have nothing in common but their symptom: one is the correct answer for a target-only
     * connector, the other a question the probe is structurally unable to ask.
     *
     * <p>There is deliberately no reason here for "its jar was not built". A connector this
     * repository cannot build is named where that is decided, and declares its modes in the overlay -
     * so it never reaches this bucket. Leaving the reason available would offer a second way out:
     * pinning a connector as unbuilt silences the same red that declaring it would have fixed, and
     * the row it leaves shipped has its mode validation switched off rather than satisfied.
     */
    private enum NoModeReason {
        /** Probed, and it registered a write function but no read function: a sink-only connector.
         *  Empty source modes are the right answer here, not a gap to close. */
        WRITE_ONLY,
        /** A JavaScript connector: no connector class exists, so the probe has nothing to open and
         *  derives nothing whatever the connector actually does. Only a declaration can answer. */
        NOT_PROBEABLE
    }

    /**
     * Bucket one: modes are empty. Eleven of seventy-eight when this baseline was taken.
     *
     * <p>Spelled out rather than derived from the artifact - a test that reads its expected population
     * off the very thing it is checking cannot fail.
     */
    private static final Map<String, NoModeReason> NO_MODES = Map.ofEntries(
            entry("ai-chat", NoModeReason.NOT_PROBEABLE),
            entry("bes-channels", NoModeReason.NOT_PROBEABLE),
            entry("lark-im", NoModeReason.NOT_PROBEABLE),
            entry("lark-task", NoModeReason.NOT_PROBEABLE),
            entry("bigquery", NoModeReason.WRITE_ONLY),
            entry("databend", NoModeReason.WRITE_ONLY),
            entry("elasticsearch", NoModeReason.WRITE_ONLY),
            entry("risingwave", NoModeReason.WRITE_ONLY),
            entry("tablestore", NoModeReason.WRITE_ONLY),
            entry("vika", NoModeReason.WRITE_ONLY),
            entry("hazelcast", NoModeReason.WRITE_ONLY));

    /**
     * What the connector is, for the rows whose modes are only a guess. Named by the family the
     * catalog put it in rather than by the mode it ought to declare: which mode is right takes the
     * connector's real semantics and a review, and this list is the input to that work, not a
     * substitute for it.
     */
    private enum Guessed {
        /** A file connector. Its reads are a directory scan, which the probe reports as the same
         *  batch and stream functions a database registers - hence the derived cdc. */
        FILE(ConnectorGroup.FILE),
        /** A SaaS connector. Its reads are HTTP calls against somebody's API, on their pagination
         *  and their rate limits - nothing the probe can tell apart from reading a table. */
        SAAS(ConnectorGroup.SAAS),
        /** A queue connector. Its read is an unbounded subscription; its two nearest siblings,
         *  kafka and kafka_enhanced, are declared stream in the overlay. */
        MQ(ConnectorGroup.MQ);

        private final ConnectorGroup group;

        Guessed(ConnectorGroup group) {
            this.group = group;
        }
    }

    /**
     * Bucket two: modes are present, derived, and on a connector derivation cannot answer for - so
     * the catalog ships a claim nobody checked. Ten of seventy-eight when this baseline was taken.
     *
     * <p>Spelled out for the same reason as the other bucket, and qualified per id so that whoever
     * writes the declaration that removes one has the starting point rather than a bare list.
     */
    private static final Map<String, Guessed> UNVERIFIED_MODES = Map.ofEntries(
            entry("csv", Guessed.FILE),
            entry("excel", Guessed.FILE),
            entry("json", Guessed.FILE),
            entry("xml", Guessed.FILE),
            entry("file-stream", Guessed.FILE),
            entry("coding", Guessed.SAAS),
            entry("http-receiver", Guessed.SAAS),
            entry("quickapi", Guessed.SAAS),
            entry("zoho-desk", Guessed.SAAS),
            entry("kafka_avro", Guessed.MQ));

    @Test
    void noConnectorJoinsTheEmptyModesBaseline() {
        List<String> joined = catalog.all().stream()
                .filter(entry -> entry.modes().isEmpty())
                .map(ConnectorCatalogEntry::id)
                .filter(id -> !NO_MODES.containsKey(id))
                .sorted()
                .toList();

        assertThat(joined)
                .as("a connector stopped resolving any mode - it is shipped with an empty mode list, "
                        + "which turns its mode validation off rather than failing it. If this is "
                        + "intended, add it to the baseline with the reason it resolved nothing")
                .isEmpty();
    }

    @Test
    void noConnectorJoinsTheUnverifiedModesBaseline() {
        // Separate from the check above, and that separation is load-bearing: an id moving between
        // the two buckets fails here while the other bucket only gets smaller, which no single
        // combined population - and no count of one bucket - would notice.
        List<String> joined = catalog.all().stream()
                .filter(ConnectorCatalogEntry::modesAreUnverified)
                .map(ConnectorCatalogEntry::id)
                .filter(id -> !UNVERIFIED_MODES.containsKey(id))
                .sorted()
                .toList();

        assertThat(joined)
                .as("a connector started shipping modes that only derivation stands behind - the "
                        + "probe cannot tell a file or a queue from a database, so these are admitted "
                        + "by validation as if somebody had declared them. Declare them, or add the "
                        + "id to the baseline with what the connector actually is")
                .isEmpty();
    }

    @Test
    void theTwoBaselinesShareNoId() {
        // The property that makes the move between buckets detectable. If an id sat in both, it could
        // move from one to the other and both checks above would still pass.
        assertThat(NO_MODES.keySet()).doesNotContainAnyElementsOf(UNVERIFIED_MODES.keySet());
    }

    @Test
    void everyQualificationStillMatchesWhatTheRowShows() {
        // A stated reason is prose, and prose rots. The part of each reason the row itself can
        // confirm is confirmed here, so a baseline whose explanation stopped being true fails rather
        // than merely misleading the next reader. Ids no longer in the catalog are skipped: a
        // connector can be dropped upstream, and a shrinking bucket is never a failure.
        List<String> contradicted = new java.util.ArrayList<>();
        for (Map.Entry<String, NoModeReason> pinned : NO_MODES.entrySet()) {
            if (!catalog.ids().contains(pinned.getKey())) {
                continue;
            }
            ConnectorCatalogEntry entry = catalog.byId(pinned.getKey());
            boolean javascript = entry.provenance().specPath() != null
                    && entry.provenance().specPath().startsWith("connectors-javascript/");
            switch (pinned.getValue()) {
                case WRITE_ONLY -> {
                    // Sink capability is only ever set from a registered write function, so this is
                    // the row's own evidence that the jar was built, opened and probed.
                    if (!entry.sink().capable()) {
                        contradicted.add(entry.id() + ": pinned WRITE_ONLY but the row is not a sink");
                    }
                }
                case NOT_PROBEABLE -> {
                    if (!javascript) {
                        contradicted.add(entry.id() + ": pinned NOT_PROBEABLE but its spec is not a "
                                + "JavaScript connector's - a class exists, so the probe could ask");
                    }
                }
            }
        }

        for (Map.Entry<String, Guessed> pinned : UNVERIFIED_MODES.entrySet()) {
            if (!catalog.ids().contains(pinned.getKey())) {
                continue;
            }
            ConnectorCatalogEntry entry = catalog.byId(pinned.getKey());
            if (entry.group() != pinned.getValue().group) {
                contradicted.add(entry.id() + ": pinned as " + pinned.getValue() + " but the catalog "
                        + "now groups it " + entry.group() + " - what it is changed, so what the "
                        + "right declaration would be changed with it");
            }
        }

        assertThat(contradicted).isEmpty();
    }

    @Test
    void theBaselinesAreReadAgainstAWholeCatalog() {
        // Both checks above pass over an empty or truncated catalog by finding nothing to complain
        // about - the exact failure they exist to catch would silence them. A floor with headroom
        // keeps them answering the question they were written for.
        assertThat(catalog.ids()).hasSizeGreaterThan(70);
        // Named ids as well as a count: a regeneration that produced seventy-odd wrong rows would
        // clear the floor. Deliberately connectors that are in neither baseline - anchoring on a
        // pinned id would make this test pass or fail with the very population it is anchoring.
        assertThat(catalog.ids()).contains("mysql", "mongodb", "postgres", "kafka");
    }
}
