package io.tapstate.core.catalog;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * Runtime access to the bundled connector catalog. The catalog is generated by the build tool and
 * shipped as static resources under {@code /catalog/}: {@code index.json}, holding the two revisions
 * the catalog was built at and the entry ids, plus one {@code <id>.json} per connector. This loads and
 * reconstructs them with no reflection, so it is free on a native image. Consumers (the wizard, validate, explain, completion) read entries here.
 */
public final class TapstateCatalog {

    private static final String INDEX = "/catalog/index.json";

    private final List<String> ids;
    private final Map<String, ConnectorCatalogEntry> byId;

    private TapstateCatalog(List<String> ids, Map<String, ConnectorCatalogEntry> byId) {
        this.ids = Collections.unmodifiableList(ids);
        this.byId = Collections.unmodifiableMap(byId);
    }

    /** Loads the bundled catalog once into an immutable instance. */
    public static TapstateCatalog load() {
        return build(resource(INDEX), id -> resource("/catalog/" + id + ".json"));
    }

    /**
     * Assembles a catalog from the index document and an entry-JSON resolver. The index carries the
     * two revisions this whole catalog was built at, and each entry gets them stamped into its
     * provenance on the way in — so what a caller reads off an entry is unchanged by their having
     * moved out of the entry files. Rejects a duplicated id so a corrupt index surfaces instead of
     * silently overwriting an entry (which would leave {@code ids()} and {@code all()} out of step).
     * Package-private so it can be driven from a test.
     */
    static TapstateCatalog build(String indexJson, Function<String, String> entryJson) {
        if (!(CatalogJson.parse(indexJson) instanceof Map<?, ?> head)) {
            throw new IllegalStateException("catalog index is not a JSON object: " + INDEX);
        }
        String specSha = string(head.get("specSha"));
        String capabilitySha = string(head.get("capabilitySha"));
        if (!(head.get("entries") instanceof List<?> indexIds)) {
            throw new IllegalStateException("catalog index has no entries array: " + INDEX);
        }
        List<String> ids = new ArrayList<>();
        Map<String, ConnectorCatalogEntry> byId = new LinkedHashMap<>();
        for (Object idValue : indexIds) {
            String id = String.valueOf(idValue);
            if (byId.containsKey(id)) {
                throw new IllegalStateException("duplicate connector id in catalog index: " + id);
            }
            ids.add(id);
            ConnectorCatalogEntry entry = CatalogEntryReader.read(entryJson.apply(id));
            byId.put(id, withShas(entry, specSha, capabilitySha));
        }
        return new TapstateCatalog(ids, byId);
    }

    private static ConnectorCatalogEntry withShas(ConnectorCatalogEntry entry,
                                                  String specSha, String capabilitySha) {
        return new ConnectorCatalogEntry(entry.id(), entry.name(), entry.displayName(), entry.icon(),
                entry.group(), entry.modes(), entry.discovery(), entry.sink(), entry.pushOut(),
                entry.config(), entry.provenance().withShas(specSha, capabilitySha));
    }

    private static String string(Object value) {
        return value == null ? null : String.valueOf(value);
    }

    /**
     * Overlays server-registered rows on the bundled snapshot to form the online catalog view. A
     * registered entry shadows a bundled one with the same id (whole-row replace; identity is
     * id-only), and a registered-only id appends after the bundled ids in the given order. Used
     * only on the online (server) side — the offline path stays on {@link #load()} so it never
     * claims a connector it cannot run.
     */
    public static TapstateCatalog merged(TapstateCatalog bundled, List<ConnectorCatalogEntry> registered) {
        List<String> ids = new ArrayList<>(bundled.ids);
        Map<String, ConnectorCatalogEntry> byId = new LinkedHashMap<>(bundled.byId);
        for (ConnectorCatalogEntry entry : registered) {
            if (!byId.containsKey(entry.id())) {
                ids.add(entry.id());
            }
            byId.put(entry.id(), entry);
        }
        return new TapstateCatalog(ids, byId);
    }

    /** Connector ids in index (catalog) order. */
    public List<String> ids() {
        return ids;
    }

    /** All entries in index order. */
    public List<ConnectorCatalogEntry> all() {
        return new ArrayList<>(byId.values());
    }

    /** The entry for {@code id}, or throws if the catalog has no such connector. */
    public ConnectorCatalogEntry byId(String id) {
        ConnectorCatalogEntry entry = byId.get(id);
        if (entry == null) {
            throw new IllegalArgumentException("no connector '" + id + "' in catalog");
        }
        return entry;
    }

    private static String resource(String path) {
        try (InputStream in = TapstateCatalog.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IllegalStateException("bundled catalog resource missing: " + path);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("reading catalog resource " + path, e);
        }
    }
}
